
development:
  adapter: postgresql
  encoding: unicode
  database: db/gamenight_development
  pool: 5
  username: randy2
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: db/gamenight_test
  pool: 5
  username: randy2
  password:
  timeout: 5000